export const profileConst = {
    PROFILE_REQUEST:'PROFILE_REQUEST',
    PROFILE_SUCCESS:'PROFILE_SUCCESS',
    PROFILE_FAILURE:'PROFILE_FAILURE',    
    PROFILE_SAVE_SUCCESS:'PROFILE_SAVE_SUCCESS',
    PROFILE_SAVE_FAILURE:'PROFILE_SAVE_FAILURE',
}
