export const quotesConst = {
    QUOTES_REQUEST : "QUOTES_REQUEST",
    QUOTES_SUCCESS : "QUOTES_SUCCESS",
    QUOTES_FAILURE : "QUOTES_FAILURE",
    QUOTES_D_SUCESS : "QUOTES_D_SUCESS",
    QUOTES_A_SUCESS : "QUOTES_A_SUCESS",
    QUOTES_G_SUCESS:"QUOTES_G_SUCESS"
}
