export const resetpasswordConst = {
    RESET_PASSWORD_SUCCESS:'RESET_PASSWORD_SUCCESS',
    RESET_PASSWORD_REQUEST:'RESET_PASSWORD_REQUEST',
    RESET_CHECKING_REQUEST:'RESET_CHECKING_REQUEST',
    RESET_PASSWORD_FAILURE:'RESET_PASSWORD_FAILURE',        
    RESET_CHECKING_FAILURE:'RESET_CHECKING_FAILURE',        
    RESET_CHECKING_SUCCESS:'RESET_CHECKING_SUCCESS',        
    RESET_SAVE_SUCCESS:'RESET_SAVE_SUCCESS',        
    RESET_SAVE_FAILURE:'RESET_SAVE_FAILURE',
    RESET_SAVE_REQUEST:'RESET_SAVE_REQUEST',        
}
